name: CI Voll Med

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build e sobe containers
      run: docker compose up -d --build

    - name: Executa testes unitários
      run: mvn -B verify
      
    - name: Gera Relatório Jacoco
      run: mvn jacoco:prepare-agent verify
      
    - name: Analise estática
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=MatheusYurirs_vollmed-api
